<?xml version="1.0" ?>
<robot name="shelf" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:include filename="$(find scene_parser)/config/utils.xacro" />

  <!-- Generic Open Shelf macro -->
  <!-- TODO add option for an open and a closed shelf -->
  <xacro:macro name="shelf" params="name
                                    frame_id
                                    xyz:='0 0 0'
                                    rpy:='0 0 0'
                                    board_number:=5
                                    board_dimensions:='0.6 1.5 0.02'
                                    post_dimensions:='0.035 0.035 1.25'
                                    dl:=_">

  <!-- Property -->
  <xacro:property name="root" value="${name}" />
  <xacro:property name="board_gap" value="${post_dim_z/(board_number)}" />

  <xacro:property name="board_dim_x" value="${board_dimensions.split()[0]}" />
  <xacro:property name="board_dim_y" value="${board_dimensions.split()[1]}" />
  <xacro:property name="board_dim_z" value="${board_dimensions.split()[2]}" />

  <xacro:property name="post_dim_x" value="${post_dimensions.split()[0]}" />
  <xacro:property name="post_dim_y" value="${post_dimensions.split()[1]}" />
  <xacro:property name="post_dim_z" value="${post_dimensions.split()[2]}" />
  

  <!-- Base link -->
  <xacro:dummy name="${root}"
               frame_id="${frame_id}"
               xyz="${xyz}" rpy="${rpy}" />

  <!-- Shelf posts -->
  <xacro:framebox name="${root}${dl}post_bl"
                  frame_id="${root}"
                  dimensions="${post_dimensions}"
                  xyz="${-(board_dim_x/2 - post_dim_x/2)} ${-(board_dim_y/2 - post_dim_y/2)}  0" />

  <xacro:framebox name="${root}${dl}post_br"
                  frame_id="${root}${dl}post_bl/bottom"
                  dimensions="${post_dimensions}"
                  xyz="0 ${board_dim_y - post_dim_y} 0"/>
  

  <xacro:framebox name="${root}${dl}post_fl"
                  frame_id="${root}${dl}post_bl/bottom"
                  dimensions="${post_dimensions}"
                  xyz="${board_dim_x - post_dim_x} 0 0"/>

  <xacro:framebox name="${root}${dl}post_fr"
                  frame_id="${root}${dl}post_fl/bottom"
                  dimensions="${post_dimensions}"
                  xyz="0 ${board_dim_y - post_dim_y} 0"/>

  <!-- Shelf boards -->
  <xacro:macro name="loop_board" params="current:=0
                                         max:=^">
    <xacro:if value="${max > current}">
      <xacro:framebox name="${root}${dl}board${current+1}"
                 frame_id="${root}"
                 dimensions="${board_dimensions}"
                 xyz="0 0 ${(current+1)*board_gap - board_dim_z}"/>
      <xacro:loop_board current="${current+1}"/>
    </xacro:if>
  </xacro:macro>

  <xacro:loop_board max="${board_number}"/>

  </xacro:macro>
</robot>

